### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by t0mtee** [wqvi/lwjgl2-wayland#1]
Following the instructions in the README gives these errors when running `ant compile_native`:
```
compile64:
    [apply] /home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/src/native/linux/opengl/context.c: In function ‘chooseVisualGLXFromBPP’:
    [apply] /home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/src/native/linux/opengl/context.c:236:9: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
    [apply]   236 |         if ( colorSamples > 0 )
    [apply]       |         ^~
    [apply] /home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/src/native/linux/opengl/context.c:237:60: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
    [apply]   237 |             putAttrib(&attrib_list, GLX_COLOR_SAMPLES_NV); putAttrib(&attrib_list, colorSamples);
    [apply]       |                                                            ^~~~~~~~~
    [apply] /home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/src/native/linux/opengl/org_lwjgl_opengl_Display.c:42:10: fatal error: GL/glew.h: No such file or directory
    [apply]    42 | #include <GL/glew.h>
    [apply]       |          ^~~~~~~~~~~
    [apply] compilation terminated.
    [apply] /home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/src/native/linux/opengl/org_lwjgl_opengl_LinuxContextImplementation.c: In function ‘Java_org_lwjgl_opengl_LinuxContextImplementation_nCreate’:
    [apply] /home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/src/native/linux/opengl/org_lwjgl_opengl_LinuxContextImplementation.c:146:21: warning: unused variable ‘context_info’ [-Wunused-variable]
    [apply]   146 |         X11Context *context_info = (*env)->GetDirectBufferAddress(env, context_handle);
    [apply]       |                     ^~~~~~~~~~~~
    [apply] /home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/src/native/linux/opengl/org_lwjgl_opengl_LinuxContextImplementation.c: At top level:
    [apply] /home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/src/native/linux/opengl/org_lwjgl_opengl_LinuxContextImplementation.c:102:13: warning: ‘createContextGLX’ defined but not used [-Wunused-function]
    [apply]   102 | static void createContextGLX(JNIEnv *env, X11PeerInfo *peer_info, X11Context *context_info, GLXContext shared_context) {
    [apply]       |             ^~~~~~~~~~~~~~~~
    [apply] /home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/src/native/linux/opengl/org_lwjgl_opengl_LinuxContextImplementation.c:79:13: warning: ‘createContextGLX13’ defined but not used [-Wunused-function]
    [apply]    79 | static void createContextGLX13(JNIEnv *env, X11PeerInfo *peer_info, X11Context *context_info, jobject attribs, GLXContext shared_context) {
    [apply]       |             ^~~~~~~~~~~~~~~~~~
    [apply] /home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/src/native/linux/opengl/org_lwjgl_opengl_LinuxContextImplementation.c:58:13: warning: ‘checkContext’ defined but not used [-Wunused-function]
    [apply]    58 | static bool checkContext(JNIEnv *env, Display *display, GLXContext context) {
    [apply]       |             ^~~~~~~~~~~~

BUILD FAILED
/home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/build.xml:491: The following error occurred while executing this line:
/home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/build.xml:525: The following error occurred while executing this line:
/home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/platform_build/linux_ant/build.xml:60: The following error occurred while executing this line:
/home/tomtee/Extras/Gaming/Minecraft/Wayland LWJGL2.9.3/platform_build/linux_ant/build.xml:97: apply returned: 1
```

If I set `-Dorg.lwjgl.librarypath=~"/Wayland LWJGL2.9.3/libs/linux"` like the README says, it gives `net.fabricmc.loader.impl.FormattedException: java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: ~/Wayland LWJGL2.9.3/libs/linux/liblwjgl64.so`, because liblwjgl64.so doesn't exist, so I'm assuming it has to be compiled.

**Comment by wqvi** [comment]
Hi t0mtee.
It seems you are missing a header for GLEW. It's a common package, so you can use your distro of choice's package manager to install it. Once you've installed it and compiled it, the UnsatisfiedLinkError should be cleared! I need to add those instructions to the README.md. If you'd like you can open a pull request and add it. Just let me know!
Thanks!

EDIT:
I updated the README. The Compilation section should include instructions to install SDL2 and GLEW. Let me know if that worked.

Another EDIT:
I added a file called lwjgl.py that is currently undocumented that assists in setting up using this library. I have failed to make the addition in the README.md that the jar file now differs from the binary. I need to do that.
First argument is instance directory typically ~/.local/share/PrismLauncher/instances/1.12.2/
Second argument is where you cloned this repository (Is this even necessary? It's a mess)

**Comment by wqvi** [comment]
I updated the README. The Compilation section should include instructions to install SDL2 and GLEW. Let me know if that worked.

**Comment by t0mtee** [comment]
Hey, so I've just gone to try all this out. It compiled all file after installing `libglew-dev`, which is great - the script doesn't quite work though. It tells me to `Make sure to compile the lwjgl2-wayland repo.`, which I have done. Seems this is happening because it's checking for `./libs/lwjgl.jar`, which doesn't exist, even after compilation.

I have to ask, will this be compatible with Legacy Fabric? That's what I'm trying to use it with - it seems they use a custom LWJGL version, and it's 2.9.4 in the first place. Is it safe to assume that'll cause issues?

**Comment by wqvi** [comment]
Hello, I might need to edit the README.md again. Try ant jars? Or just try executing ant. That should produce ./libs/lwjgl.jar.

As for legacy fabric. No unfortunately it isn't compatible. However, if that is something you are interested in could you point me in that direction? I am curious myself as to what that is.

**Comment by t0mtee** [comment]
Those commands worked (both produced lwjgl.jar, I think only one of the two needs to be ran).

Legacy Fabric is a fork of Fabric that intends to support legacy Minecraft versions: [https://legacyfabric.net/](https://legacyfabric.net/). This should be where their lwjgl version is stored: [https://github.com/Legacy-Fabric/lwjgl](https://github.com/Legacy-Fabric/lwjgl). It would be great if you could support it but there's no pressure :)

**Comment by wqvi** [comment]
So you were able to successfully run Minecraft? If so I will close this issue! Thank you for your issue report, the first for this repo!

**Comment by t0mtee** [comment]
Apologies, I hadn't set up a 1.8.9 instance to test the compiled jar, was just noting that it had compiled.
Sorry, as there are more errors. The first comes if no Java argument is set:
```
[14:36:43] [Client thread/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
[14:36:44] [Client thread/INFO]: LWJGL Version: 2.9.3
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7181d10bac, pid=36451, tid=0x00007f7182d2c6c0
#
# JRE version: OpenJDK Runtime Environment (8.0_422-b05) (build 1.8.0_422-b05)
# Java VM: OpenJDK 64-Bit Server VM (25.422-b05 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x710bac]  jni_IsInstanceOf+0x6c
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/tomtee/.local/share/PrismLauncher/instances/1.8.9/.minecraft/hs_err_pid36451.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
```
The second comes if org.lwjgl.librarypath is set to where liblwjgl64.so is stored:
```
[14:37:51] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Failed to initialize glew
	at org.lwjgl.opengl.LinuxDisplay.nCreateWindow(Native Method) ~[lwjgl.jar:?]
	at org.lwjgl.opengl.LinuxDisplay.createWindow(LinuxDisplay.java:322) ~[lwjgl.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:297) ~[lwjgl.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:809) ~[lwjgl.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:718) ~[lwjgl.jar:?]
	at ave.ap(SourceFile:521) [minecraft-1.8.9-client.jar:?]
	at ave.am(SourceFile:363) [minecraft-1.8.9-client.jar:?]
	at ave.a(SourceFile:310) [minecraft-1.8.9-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [minecraft-1.8.9-client.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 13/10/24 14:37
Description: Initializing game

org.lwjgl.LWJGLException: Failed to initialize glew
	at org.lwjgl.opengl.LinuxDisplay.nCreateWindow(Native Method)
	at org.lwjgl.opengl.LinuxDisplay.createWindow(LinuxDisplay.java:322)
	at org.lwjgl.opengl.Display.createWindow(Display.java:297)
	at org.lwjgl.opengl.Display.create(Display.java:809)
	at org.lwjgl.opengl.Display.create(Display.java:718)
	at org.lwjgl.opengl.Display.create(Display.java:700)
	at ave.ap(SourceFile:534)
	at ave.am(SourceFile:363)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.LinuxDisplay.nCreateWindow(Native Method)
	at org.lwjgl.opengl.LinuxDisplay.createWindow(LinuxDisplay.java:322)
	at org.lwjgl.opengl.Display.createWindow(Display.java:297)
	at org.lwjgl.opengl.Display.create(Display.java:809)
	at org.lwjgl.opengl.Display.create(Display.java:718)
	at org.lwjgl.opengl.Display.create(Display.java:700)
	at ave.ap(SourceFile:534)
	at ave.am(SourceFile:363)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 6.10.11+bpo-amd64
	Java Version: 1.8.0_422, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 584203552 bytes (557 MB) / 649592832 bytes (619 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.9
	LWJGL: 2.9.3
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/tomtee/.local/share/PrismLauncher/instances/1.8.9/.minecraft/crash-reports/crash-2024-10-13_14.37.52-client.txt
[14:37:52] [Client Shutdown Thread/INFO]: Stopping server
```

**Comment by wqvi** [comment]
I will start investigating this.

**Comment by wqvi** [comment]
The top issue is expected from what I can tell. You need to override the native library else it won't work.

Can I get information about your system? I am curious about what versions of mesa, SDL2, and GLEW you are using. Also what kind of GPU are you using? I am trying to diagnose the glewInit failure.

**Comment by t0mtee** [comment]
I've got an RX 6700 XT, but am actually on mesa 22.3.6 (I'm on Debian). They recently backported mesa 24 but I've had an issue while updating that which I'm trying to solve.
SDL is 2.26.5 and GLEW is 2.2.0-4

**Comment by wqvi** [comment]
I updated main to include a slightly more verbose glew error exception. See what that produces. I am not sure what would be causing this issue.

**Comment by t0mtee** [comment]
So I've updated mesa to 24.2.2 and recompiled this and have a new error: https://pastebin.com/Qj8AmEsZ
Thank you so much for helping so far :)

**Comment by wqvi** [comment]
Do you have an environment variable SDL_VIDEODRIVER=wayland? I am stumped LOL

What about running just a simple hello world with glewInit? I know that seems silly but it might be worth trying.

```
#include <GL/glew.h>
#define NO_SDL_GLEXT
#include <SDL2/SDL.h>
#include <SDL2/SDL_opengl.h>

int main(void) {
  if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS) < 0) {
    return 1;
  }
  SDL_Window *win = SDL_CreateWindow("win", 0, 0, 640, 480, SDL_WINDOW_OPENGL);
  if (!win) {
    return 2;
  }
  SDL_GL_SetAttribute(SDL_GL_MAJOR_VERSION, 2);
  SDL_GL_SetAttribute(SDL_GL_MINOR_VERSION, 1);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_COMPATIBILITY);
  SDL_GLContext c = SDL_GL_CreateContext(win);
  if (!c) {
    return 3;
  }
  SDL_GL_MakeCurrent(win, c);
  glewExperimental = GL_FALSE;
  if (glewInit() != GLEW_OK) {
    return 4;
  }
  SDL_GL_DeleteContext(c);
  SDL_DestroyWindow(win);
  SDL_Quit();
  return 0;
}
```
Compile it with
```
gcc main.c $(pkg-config --libs --cflags sdl2 glew)
```
Run it.
And give me the exit code, through `$?`

**Comment by t0mtee** [comment]
So I've compiled it (had to change SDL_GL_MAJOR/MINOR_VERSION to SDL_MAJOR/MINOR_VERSION) and when running it, I get a black screen that pops up then disappears. Using `echo $?` returns 0.

Adding SDL_VIDEODRIVER=wayland to my instances environment variables doesn't change the error message.

**Comment by wqvi** [comment]
The values of SDL_MAJOR/MINOR_VERSION stayed the same though yes? I'll poke around again later today. I appreciate your patience!

**Comment by t0mtee** [comment]
Yes, all I changed was getting rid of the "_GL".
Thank you for being patient with me! I greatly appreciate all of this.

**Comment by wqvi** [comment]
Hi I just added a couple lines of code to src/common/opengl/org_lwjgl_opengl_GLContext.c that print the name of requested function and it's returned function address. I think I have an idea as to what is going wrong. There is still GLX functionality in the codebase which can be causing the null ptr. Just post another pastebin with the output (this will probably be a long one). Thanks!

**Comment by t0mtee** [comment]
Here you are! https://pastebin.com/uqTL6Rky

**Comment by wqvi** [comment]
Can you run `glewinfo` (might want to use grep or less) and give me the OpenGL version? Should look something like so: "OpenGL version 4.6 (Compatibility Profile) Mesa 24.1.7 is supported"

**Comment by t0mtee** [comment]
GLEW version 2.2.0
OpenGL version 4.6 (Compatibility Profile) Mesa 24.2.2-1~bpo12+1 is supported

**Comment by wqvi** [comment]
Hi so I added the proper debug info, ie SDL_GetError, and glewGetErrorString. If you could update your local repo compile and send me that error, I might actually be able to do something with that, thanks! (I am so sorry for sending you on a wild goose chase)

**Comment by t0mtee** [comment]
Seriously, don't worry about it! I'm sorry for sending YOU on a wild goose chase - I have the issue afterall haha.
Here's my log: https://pastebin.com/6w8RLeAN

**Comment by wqvi** [comment]
Hi so I found similar issues. [glew on wayland issue](https://github.com/nigels-com/glew/issues/172) and [vtk on wayland issue referencing glew issue](https://gitlab.kitware.com/vtk/vtk/-/issues/19357). This might mean I have to switch libraries. I am going to try what nigels-com suggested in the glew issue, which is to use glewContextInit(). If that doesn't work then I will have switch libraries. I was thinking [libepoxy](https://github.com/anholt/libepoxy).

Edit:
It seems the glewContextInit is not rolled to my distro of choice's glew header. So yep gonna switch libraries. This might take me a while, I will create a new branch called _libepoxy_. I will keep you updated when it is ready to be tried!

**Comment by wqvi** [comment]
Wow libepoxy was surprisingly simple to setup. It's ready to be tried out!

**Comment by t0mtee** [comment]
It's all working now! That's brilliant, thank you so much for working with me. Happy to close the issue here :)
